/*
Handling exceptions using throws keyword
Another way of handling exception Is using throws keyword with method as shown In bellow given example. 
Supposing you have a throwexc method which Is throwing some exception and this method Is called from some other method catchexc. 
Now you wants to handle exception of throwexc method In to catchexc method then you need to use throws keyword with throwexc method.
*/

public class Handle_exce { 
 
 public static void main(String[] args) {
  catchexc();
 }
 private static void catchexc() {
     try {
      //throwexc() Method called.
      throwexc();
     } catch (ArithmeticException e) { //Exception of throwexc() will be caught here and take required action.
         System.out.println("Devide by 0 error.");
     }
 } 
 //This method will throw ArithmeticException divide by 0.
 private static void throwexc() throws ArithmeticException {  
     int i=15/0;     
 } 
}
